// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRole) DeepCopyInto(out *AppRole) {
	*out = *in
	if in.TokenNumUses != nil {
		in, out := &in.TokenNumUses, &out.TokenNumUses
		*out = new(int32)
		**out = **in
	}
	if in.SecretIdNumUses != nil {
		in, out := &in.SecretIdNumUses, &out.SecretIdNumUses
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRole.
func (in *AppRole) DeepCopy() *AppRole {
	if in == nil {
		return nil
	}
	out := new(AppRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthBackend) DeepCopyInto(out *AuthBackend) {
	*out = *in
	in.AppRoleAuth.DeepCopyInto(&out.AppRoleAuth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthBackend.
func (in *AuthBackend) DeepCopy() *AuthBackend {
	if in == nil {
		return nil
	}
	out := new(AuthBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpRole) DeepCopyInto(out *GcpRole) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BoundProjects != nil {
		in, out := &in.BoundProjects, &out.BoundProjects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BoundZones != nil {
		in, out := &in.BoundZones, &out.BoundZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BoundLabels != nil {
		in, out := &in.BoundLabels, &out.BoundLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BoundServiceAccounts != nil {
		in, out := &in.BoundServiceAccounts, &out.BoundServiceAccounts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpRole.
func (in *GcpRole) DeepCopy() *GcpRole {
	if in == nil {
		return nil
	}
	out := new(GcpRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretBackend) DeepCopyInto(out *SecretBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretBackend.
func (in *SecretBackend) DeepCopy() *SecretBackend {
	if in == nil {
		return nil
	}
	out := new(SecretBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vaultapp) DeepCopyInto(out *Vaultapp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vaultapp.
func (in *Vaultapp) DeepCopy() *Vaultapp {
	if in == nil {
		return nil
	}
	out := new(Vaultapp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Vaultapp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultappList) DeepCopyInto(out *VaultappList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vaultapp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultappList.
func (in *VaultappList) DeepCopy() *VaultappList {
	if in == nil {
		return nil
	}
	out := new(VaultappList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultappList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultappSpec) DeepCopyInto(out *VaultappSpec) {
	*out = *in
	in.AuthBackend.DeepCopyInto(&out.AuthBackend)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultappSpec.
func (in *VaultappSpec) DeepCopy() *VaultappSpec {
	if in == nil {
		return nil
	}
	out := new(VaultappSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultappStatus) DeepCopyInto(out *VaultappStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultappStatus.
func (in *VaultappStatus) DeepCopy() *VaultappStatus {
	if in == nil {
		return nil
	}
	out := new(VaultappStatus)
	in.DeepCopyInto(out)
	return out
}
