name: my-demo

on:
  push:

jobs:
  hello-devops-bfs:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello to us!"

    - uses: actions/checkout@v3
    - name: cat some file
      run: cat Makefile

  build:
    runs-on: ubuntu-latest
    needs:
    - hello-devops-bfs

    steps:
    - uses: actions/checkout@v3
    - name: build our go code
      run: go build
