name: my-demo

on:
  push:

jobs:
  hello-devops-bfs:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello to us!"

    - uses: actions/checkout@v3
    - name: cat some file
      run: cat Makefile

  build:
    runs-on: ubuntu-latest
    needs:
    - hello-devops-bfs

    steps:
    - uses: actions/checkout@v3
    - name: build our go code
      run: go build

  docker:
    runs-on: ubuntu-latest
    needs:
    - build

    steps:
    - uses: actions/checkout@v3
    - name: build docker
      run: |
        docker build -t mycontainer .
        docker tag mycontainer gadjrussell/mycontainer:latest

    - name: login
      run: docker gadjrussell --username foo --password dckr_pat_tv_VTc0NiBkMfKUEkdbHTPELi4I

    - name: push to dockerhub
      run: docker push gadjrussell/mycontainer:latest
