name: my-demo

on:
  push:

jobs:
  hello-devops-bfs:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello to us!"

    - uses: actions/checkout@v3
    - name: cat some file
      run: cat Makefile

